shimmerproject/elementary-xfce

- Makefile.in
- svgtopng/Makefile
The commits in this pull request address two Makefile changes I required to make on FreeBSD while updating the port to the latest version.
I anyway think these changes are of general interest and can be useful on other OSes too.
> FreeBSD build fixes

- elementary-xfce-dark/panel/22/blueberry-tray-active.svg
- elementary-xfce-dark/panel/22/blueberry-tray-disabled.svg
- elementary-xfce-dark/panel/22/blueberry-tray.svg
- elementary-xfce-dark/panel/24/blueberry-tray-active.svg
- elementary-xfce-dark/panel/24/blueberry-tray-disabled.svg
- elementary-xfce-dark/panel/24/blueberry-tray.svg
- elementary-xfce/panel/22/blueberry-tray-active.svg
- elementary-xfce/panel/22/blueberry-tray-disabled.svg
- elementary-xfce/panel/22/blueberry-tray.svg
- elementary-xfce/panel/24/blueberry-tray-active.svg
- elementary-xfce/panel/24/blueberry-tray-disabled.svg
- elementary-xfce/panel/24/blueberry-tray.svg
Added symlinks for blueberry tray icons based on standard bluetooth icons
> added blueberry tray icons

- elementary-xfce-dark/panel/24/software-update-available.svg
- elementary-xfce-dark/panel/24/software-update-urgent.svg
- elementary-xfce-dark/panel/24/system-software-update.svg
- elementary-xfce/panel/24/software-update-available.svg
- elementary-xfce/panel/24/software-update-urgent.svg
- elementary-xfce/panel/24/system-software-update.svg
Some users using 24px icons had this missing and requested it.
> Added 24px system-software-update mochrome icons

- elementary-xfce/status/symbolic/transmission-tray-icon-symbolic.svg
> Added transmission symbolic icon

- elementary-xfce-dark/panel/16/software-update-available.svg
- elementary-xfce-dark/panel/22/software-update-available.svg
- elementary-xfce-dark/panel/24/software-update-available.svg
- elementary-xfce/panel/16/software-update-available.svg
- elementary-xfce/panel/22/software-update-available.svg
- elementary-xfce/panel/24/software-update-available.svg
software-updater non symbolic icons to use the same color codes as the symbolic icons, defined by class "warning" for update available and "error" for urgent updates
> updated software-updater icons to match symbolic icons color codes

- elementary-xfce/places/16/folder-music.svg
- elementary-xfce/places/24/folder-music.svg
The icon is more visible when using a dark theme
> Make 16-24px Music folder blue for better contrast on dark background

- elementary-xfce/actions/24/go-home.svg
Use the same icon style for the home folder used in 16px because it's nicer
> Make 24px home folder consistent with 16px

- elementary-xfce-darker/actions/24/go-home.svg
Just a small fix to make darker theme consistent with the rest
> Fix home icon in darker theme

- elementary-xfce-dark/panel/24/clipman.svg
Partially fixes issue #193. I'll leave the xfpm be for now
> Add 24px clipman icon

- elementary-xfce/apps/128/gufw.svg
- elementary-xfce/apps/16/gufw.svg
- elementary-xfce/apps/24/gufw.svg
- elementary-xfce/apps/32/gufw.svg
- elementary-xfce/apps/48/gufw.svg
- elementary-xfce/apps/64/gufw.svg
- elementary-xfce/apps/96/gufw.svg
- elementary-xfce/devices/128/network-firewall.svg
- elementary-xfce/devices/16/network-firewall.svg
- elementary-xfce/devices/24/network-firewall.svg
- elementary-xfce/devices/64/network-firewall.svg
- elementary-xfce/devices/96/network-firewall.svg
Tried to adjust the current elementary firewall icon to make it use the newer palette and look a little sharper. Added missing sizes. Added symlink for gufw.
> Add firewall icon at all sizes, gufw app symlink

- elementary-xfce/actions/16/add-files-to-archive.svg
- elementary-xfce/actions/16/add-folder-to-archive.svg
- elementary-xfce/actions/16/archive-insert-directory.svg
- elementary-xfce/actions/16/archive-insert.svg
- elementary-xfce/actions/16/extract-archive.svg
- elementary-xfce/actions/16/tap-create.svg
- elementary-xfce/actions/16/tap-extract-to.svg
- elementary-xfce/actions/16/tap-extract.svg
- elementary-xfce/actions/24/archive-insert-directory.svg
- elementary-xfce/actions/24/archive-insert.svg
- elementary-xfce/actions/24/extract-archive.svg
- elementary-xfce/actions/24/xarchiver-add.svg
- elementary-xfce/actions/24/xarchiver-extract.svg
- elementary-xfce/actions/48/archive-extract.svg
- elementary-xfce/actions/48/archive-insert-directory.svg
- elementary-xfce/actions/48/archive-insert.svg
Should now have the same look more similar at
all sizes and use newer assets, styles, and borders.
Adds icons for xarchiver, engrampa, and
thunar archive plugin (right click menu on files).
> Update archive action icons

- .github/workflows/pull-request.yml
- .github/workflows/symlinks-check.yml
On a pull request: build the tarball and add a comment to the PR with a link to the resource.
On push to master: run the standard symlink check.
> ci: Build a release tarball on PRs (Fixes #312)

- elementary-xfce/actions/24/edit-redo-symbolic.svg
- elementary-xfce/actions/24/edit-undo-symbolic.svg
- elementary-xfce/actions/32/view-grid-symbolic.svg
- elementary-xfce/actions/32/view-list-compact-symbolic.svg
- elementary-xfce/actions/32/view-list-symbolic.svg
- elementary-xfce/actions/32/view-list-tree-symbolic.svg
Add symbolic icons for:
- Whisker preferences window (app/icon view).
- Thunar undo and redo toolbar buttons.
> Add symbolic icons for Whisker, Thunar

- .github/workflows/pull-request.yml
- .github/workflows/symlinks-check.yml
Should fix issue where apt install is unable to find new packages, causing the checks to fail.
I'm not that familiar with Github actions so I hope this is the right thing to do. If not I apologize.
> Add apt-get update to github actions

- elementary-xfce/places/128/user-trash-full.svg
- elementary-xfce/places/128/user-trash.svg
- elementary-xfce/places/96/user-trash-full.svg
- elementary-xfce/places/96/user-trash.svg
> Places: Add Trash at 96px and 128px

- elementary-xfce/actions/16/view-fullscreen.svg
- elementary-xfce/actions/16/view-restore.svg
- elementary-xfce/actions/16/view-sort-ascending.svg
- elementary-xfce/actions/24/view-fullscreen.svg
- elementary-xfce/actions/24/view-restore.svg
- elementary-xfce/actions/32/view-fullscreen.svg
- elementary-xfce/actions/32/view-restore.svg
- elementary-xfce/actions/48/view-fullscreen.svg
- elementary-xfce/actions/48/view-restore.svg
Use rounded arrow, semi-transparent borders and highlights, and newer palette for `view-fullscreen` and `view-restore`
Also fixed issue where 16px `view-sort-ascending` gradients were upside down.
> Actions: Refresh view-fullscreen, view-restore

- elementary-xfce/apps/128/org.xfce.notification.svg
- elementary-xfce/apps/16/org.xfce.notification.svg
- elementary-xfce/apps/24/org.xfce.notification.svg
- elementary-xfce/apps/32/org.xfce.notification.svg
- elementary-xfce/apps/96/org.xfce.notification.svg
Use the yellow bell for the notification app icon.
This matches the status notification icon, and is closer the Xfce notifyd icon.
Also more closely matched the elementary style.
> Apps: Use bell style for notification app

- elementary-xfce/mimes/16/application-msword.svg
- elementary-xfce/mimes/16/application-vnd.ms-excel.svg
- elementary-xfce/mimes/16/application-vnd.ms-powerpoint.svg
- elementary-xfce/mimes/16/application-vnd.openxmlformats-officedocument.presentationml.template.svg
- elementary-xfce/mimes/16/application-vnd.openxmlformats-officedocument.spreadsheetml.template.svg
- elementary-xfce/mimes/16/application-vnd.openxmlformats-officedocument.wordprocessingml.template.svg
- elementary-xfce/mimes/24/application-msword.svg
- elementary-xfce/mimes/24/application-vnd.ms-excel.svg
- elementary-xfce/mimes/24/application-vnd.ms-powerpoint.svg
- elementary-xfce/mimes/24/application-vnd.openxmlformats-officedocument.presentationml.template.svg
- elementary-xfce/mimes/24/application-vnd.openxmlformats-officedocument.spreadsheetml.template.svg
- elementary-xfce/mimes/24/application-vnd.openxmlformats-officedocument.wordprocessingml.template.svg
- elementary-xfce/mimes/32/application-vnd.ms-excel.svg
- elementary-xfce/mimes/32/application-vnd.ms-powerpoint.svg
- elementary-xfce/mimes/32/application-vnd.openxmlformats-officedocument.presentationml.template.svg
- elementary-xfce/mimes/32/application-vnd.openxmlformats-officedocument.spreadsheetml.template.svg
- elementary-xfce/mimes/48/application-msword.svg
- elementary-xfce/mimes/48/application-vnd.ms-excel.svg
- elementary-xfce/mimes/48/application-vnd.ms-powerpoint.svg
- elementary-xfce/mimes/48/application-vnd.openxmlformats-officedocument.presentationml.template.svg
- elementary-xfce/mimes/48/application-vnd.openxmlformats-officedocument.spreadsheetml.template.svg
- elementary-xfce/mimes/48/application-vnd.openxmlformats-officedocument.wordprocessingml.template.svg
Doesn't seem to make much of a difference at 16px but hopefully larger sizes look a little cleaner.
> Mimes: Grid-align office icons

- elementary-xfce/apps/128/accessories-dictionary.svg
- elementary-xfce/apps/128/qbittorrent.svg
- elementary-xfce/apps/128/time-admin.svg
- elementary-xfce/apps/128/wine.svg
- elementary-xfce/apps/16/accessories-dictionary.svg
- elementary-xfce/apps/16/qbittorrent.svg
- elementary-xfce/apps/16/time-admin.svg
- elementary-xfce/apps/24/accessories-dictionary.svg
- elementary-xfce/apps/24/qbittorrent.svg
- elementary-xfce/apps/32/accessories-dictionary.svg
- elementary-xfce/apps/32/qbittorrent.svg
- elementary-xfce/apps/32/time-admin.svg
- elementary-xfce/apps/32/wine.svg
- elementary-xfce/apps/48/accessories-dictionary.svg
- elementary-xfce/apps/48/qbittorrent.svg
- elementary-xfce/apps/64/accessories-dictionary.svg
- elementary-xfce/apps/64/qbittorrent.svg
- elementary-xfce/apps/64/time-admin.svg
- elementary-xfce/apps/64/wine.svg
- elementary-xfce/apps/96/accessories-dictionary.svg
- elementary-xfce/apps/96/qbittorrent.svg
- elementary-xfce/apps/96/time-admin.svg
- elementary-xfce/apps/96/wine.svg
New
- qBittorrent
Refreshed
- Dictionary
Updated
- time-admin (rounded corners, semi-transparent borders, add missing sizes)
- wine (semi-transparent borders, add missing sizes)
For Reference: Used Noto Serif font for Dictionary
> Apps: Add qBittorrent, refresh Dictionary

- elementary-xfce/apps/128/utilities-system-monitor.svg
- elementary-xfce/apps/16/utilities-system-monitor.svg
- elementary-xfce/apps/22/utilities-system-monitor.svg
- elementary-xfce/apps/24/utilities-system-monitor.svg
- elementary-xfce/apps/48/utilities-system-monitor.svg
- elementary-xfce/apps/96/utilities-system-monitor.svg
Refresh of the system monitor / task manager icon. Uses newer elementary rounded-square style and semitransparent borders.
> Apps: Refresh system monitor / task manager icon

- elementary-xfce/devices/22/drive-removable-media-usb.svg
Fixes https://github.com/elementary/icons/issues/1243
Fixes #423
> Devices: Fix incorrectly sized USB icon at 22px

- elementary-xfce/status/16/weather-clear-night.svg
- elementary-xfce/status/16/weather-overcast.svg
- elementary-xfce/status/16/weather-severe-alert.svg
- elementary-xfce/status/16/weather-showers-scattered.svg
- elementary-xfce/status/16/weather-showers.svg
- elementary-xfce/status/16/weather-storm.svg
Add missing weather icons per the FreeDesktop.org Icon Naming Specification
https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
Not sure if these are used anywhere, but they are in the spec!
> Status: Add weather icons for FreeDesktop

- elementary-xfce/mimetypes/128/application-vnd.efi.img.svg
- elementary-xfce/mimetypes/16/application-vnd.efi.img.svg
- elementary-xfce/mimetypes/24/application-vnd.efi.img.svg
- elementary-xfce/mimetypes/32/application-vnd.efi.img.svg
- elementary-xfce/mimetypes/48/application-vnd.efi.img.svg
- elementary-xfce/mimetypes/64/application-vnd.efi.img.svg
- elementary-xfce/mimetypes/96/application-vnd.efi.img.svg
Proposal for new mimetype icon for disk images. Any thoughts would be appreciated!
Fixes #234
> MimeTypes: Add disk image icon
