shimmerproject/elementary-xfce

- elementary-xfce/apps/24/mate-disk-usage-analyzer.svg
- elementary-xfce/apps/48/mate-disk-usage-analyzer.svg
- elementary-xfce/apps/64/mate-disk-usage-analyzer.svg
At least in Arch Linux mate-disk-usage-analyzer.desktop is looking for them.
> Add symbolic links for some Mate Disk Usage Analyzer

- elementary-xfce/mimes/16/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/16/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/16/application-vnd.visio.svg
- elementary-xfce/mimes/22/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/22/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/22/application-vnd.visio.svg
- elementary-xfce/mimes/24/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/24/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/24/application-vnd.visio.svg
- elementary-xfce/mimes/32/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/32/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/32/application-vnd.visio.svg
- elementary-xfce/mimes/48/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/48/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/48/application-vnd.visio.svg
- elementary-xfce/mimes/64/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/64/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/64/application-vnd.visio.svg
- elementary-xfce/mimes/96/application-vnd.ms-visio.drawing.main+xml.svg
- elementary-xfce/mimes/96/application-vnd.ms-visio.template.main+xml.svg
- elementary-xfce/mimes/96/application-vnd.visio.svg
Currently elementary theme do not support visio icons. This PR fixes it.
Also I've added (http://cgit.freedesktop.org/xdg/shared-mime-info/commit/?id=d1022b00c120f477060714d0b5c0cbe6211e4b23) vsdx and vstx file-type support to share-mime-info project, so to test it you should build latest shared-mime-info.
To verify my symlinks use mime-type database http://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in
More info about this filetypes http://fileinfo.com/software/microsoft/visio
> Added support for vsd, vsdx and vstx

- elementary-xfce/index.theme
gnome-icon-theme has been renamed to adwaita-icon-theme back in 2014
and gnome-icon-theme has been archived.
Since we already inherit adwaita, which in fact is a renamed gnome-icon-theme,
we no longer have to care for the old name.
> No longer inherit from the gnome icon theme

- CONTRIBUTORS
- elementary-xfce-dark/panel/16/software-update-available.svg
- elementary-xfce-dark/panel/16/software-update-urgent.svg
- elementary-xfce-dark/panel/16/system-software-update.svg
- elementary-xfce-dark/panel/22/software-update-available.svg
- elementary-xfce-dark/panel/22/software-update-urgent.svg
- elementary-xfce-dark/panel/22/system-software-update.svg
- elementary-xfce/panel/16/software-update-available.svg
- elementary-xfce/panel/16/software-update-urgent.svg
- elementary-xfce/panel/16/system-software-update.svg
- elementary-xfce/panel/22/software-update-available.svg
- elementary-xfce/panel/22/software-update-urgent.svg
- elementary-xfce/panel/22/system-software-update.svg
This is the finalized version of software updater monochrome icons for the panel systray/indicator  as discussed in PR #143.
No update:
Update available:
Urgent update available:
> Add approved 'monochrome' panel icons for software updater

- elementary-xfce-dark/apps/48/system-software-update.svg
- elementary-xfce-darker/apps/48/system-software-update.svg
- elementary-xfce-darker/index.theme
As shown in the screenshot this commit changes the header icon for gnome-packagekit appropriately.
> adding symlink to appropriate update icon for gpk

- elementary-xfce-darker/apps/48/system-software-update.svg
- elementary-xfce-darker/index.theme
The 48px icon overrides the panel monochrome one. Adding the icons in the Darker variant is not necessary because it already inherits from Dark.
> Remove not needed system-software-update.svg from "darker" theme variant

- elementary-xfce/status/symbolic/blueman-disabled-symbolic.svg
- elementary-xfce/status/symbolic/software-update-urgent-symbolic.svg
- elementary-xfce/status/symbolic/system-software-update-symbolic.svg
blueman-disabled icon is displayed as the 22px instead of the symbolic one due to a missing symlink
> fixed blueman-disabled symbolic icon and added new sofware-updater symbolic icons

- elementary-xfce/status/symbolic/blueberry-tray-active-symbolic.svg
- elementary-xfce/status/symbolic/blueberry-tray-disabled-symbolic.svg
- elementary-xfce/status/symbolic/blueberry-tray-symbolic.svg
- elementary-xfce/status/symbolic/blueman-active-symbolic.svg
- elementary-xfce/status/symbolic/blueman-symbolic.svg
Apparently appindicators don't use the *-tray-symbolic.svg icons. Created symlinks with correct icon name for blueman. Also added missing blueberry symbolic icons
> Add some missing symbolic icons for blueman and blueberry

- elementary-xfce/status/symbolic/nm-device-wired-symbolic.svg
The icon is a symlink of the existing network-wired-symbolic.svg
> Added nm-applet wired symbolic icon

- elementary-xfce-dark/apps/128/blueman.svg
- elementary-xfce-dark/apps/128/utilities-terminal.svg
- elementary-xfce/apps/128/blueman.svg
- elementary-xfce/apps/128/bluetooth.svg
Because of missing 128px icons in Dark and Darker, they don't scale right in help dialogs.
> Fix xfce4-terminal and blueman icons used in help dialogs

- elementary-xfce/devices/128/drive-removable-media-usb.svg
- elementary-xfce/devices/16/drive-removable-media-usb.svg
- elementary-xfce/devices/24/drive-removable-media-usb.svg
- elementary-xfce/devices/32/drive-removable-media-usb.svg
- elementary-xfce/devices/48/drive-removable-media-usb.svg
- elementary-xfce/devices/64/drive-removable-media-usb.svg
- elementary-xfce/devices/96/drive-removable-media-usb.svg
Removable USB device icon was missing above 48px.
This pulls the current icon from upstream for
sizes 16, 24, 32, 48, 64, 128, and from those
creates a new 96px icon.
Fixes #213
> Update removable USB device icon (Fixes #213)

- elementary-xfce/places/128/user-desktop.svg
- elementary-xfce/places/16/user-desktop.svg
- elementary-xfce/places/22/user-desktop.svg
- elementary-xfce/places/24/user-desktop.svg
- elementary-xfce/places/32/user-desktop.svg
- elementary-xfce/places/48/user-desktop.svg
- elementary-xfce/places/64/user-desktop.svg
The desktop icon is one of the few places icons
that has not seen a refresh, leaving the current
desktop icon looking a little bit dated.
This one is  brighter, cleaner, and better matches
the folder colors, gradients, outlines, and curves.
The sizing has also been adjusted to match the width
and height of the folders. This should also blend in
better with the newly designed Xfce app icons.
New:
Current:
> Add new desktop places icon

- elementary-xfce/devices/48/gnome-dev-symlink.svg
Fixes a symlink that was broken by bd91423f954b3770d64cfbc542eca796a1cd474a
> Update broken symlink

- elementary-xfce/actions/16/format-indent-less.svg
- elementary-xfce/actions/16/format-indent-more.svg
- elementary-xfce/actions/16/gtk-index.svg
- elementary-xfce/actions/16/view-sort-ascending.svg
- elementary-xfce/actions/16/view-sort-descending.svg
- elementary-xfce/actions/24/gtk-index.svg
- elementary-xfce/actions/24/view-page-continuous.svg
- elementary-xfce/actions/24/view-page-facing.svg
- elementary-xfce/actions/symbolic/sidebar-hide-symbolic.svg
- elementary-xfce/actions/symbolic/sidebar-places-symbolic.svg
- elementary-xfce/actions/symbolic/sidebar-show-symbolic.svg
- elementary-xfce/actions/symbolic/sidebar-tree-symbolic.svg
- elementary-xfce/apps/128/org.xfce.mailreader.svg
- elementary-xfce/apps/128/org.xfce.panel.svg
- elementary-xfce/apps/128/xfce4-panel.svg
- elementary-xfce/apps/16/org.xfce.mailreader.svg
- elementary-xfce/apps/22/org.xfce.mailreader.svg
- elementary-xfce/apps/24/org.xfce.mailreader.svg
- elementary-xfce/apps/32/org.xfce.mailreader.svg
- elementary-xfce/apps/48/org.xfce.mailreader.svg
- elementary-xfce/apps/64/org.xfce.mailreader.svg
Adds a few missing icons used by some apps.
Whisker Menu and Applications Menu
- org.xfce.mailreader
Mousepad
- format-indent-more
- format-indent-less
Atril and Xarchiver
- gtk-index
- view-page-continuous
- view-page-facing
Xfdesktop (and other apps)
- view-sort-ascending
- view-sort-descending
Sidebar icons
- Used for some app's sidebars
Xfce Panel icon at 128px
- For Panel > About
Fixes #250
> Add missing icons

- .github/workflows/symlinks.yml
- Makefile.in
- svgtopng/pngtheme.sh
Create a 'make test' target that skips the png optimization because that
would be a waste of time in CI. Also the pngtheme.sh script now fails if
dangling symlinks are detected.
> Add GitHub action to test for dangling symlinks

- elementary-xfce-darker/actions/24/xfsm-hibernate.svg
- elementary-xfce-darker/actions/24/xfsm-lock.svg
- elementary-xfce-darker/actions/24/xfsm-logout.svg
- elementary-xfce-darker/actions/24/xfsm-reboot.svg
- elementary-xfce-darker/actions/24/xfsm-shutdown.svg
- elementary-xfce-darker/actions/24/xfsm-suspend.svg
- elementary-xfce-darker/actions/24/xfsm-switch-user.svg
Resymlinked newer xfsm icons to darker theme to fix
issue where they didn't show in Whisker menu on
darker and darkest themes.
> Fix issue where xfsm icons don't show in darker

- elementary-xfce/apps/128/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/128/lightdm-settings.svg
- elementary-xfce/apps/128/mugshot.svg
- elementary-xfce/apps/16/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/16/lightdm-settings.svg
- elementary-xfce/apps/16/mugshot.svg
- elementary-xfce/apps/24/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/24/lightdm-settings.svg
- elementary-xfce/apps/24/mugshot.svg
- elementary-xfce/apps/32/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/32/lightdm-settings.svg
- elementary-xfce/apps/32/mugshot.svg
- elementary-xfce/apps/48/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/48/lightdm-settings.svg
- elementary-xfce/apps/48/mugshot.svg
- elementary-xfce/apps/64/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/64/lightdm-settings.svg
- elementary-xfce/apps/64/mugshot.svg
- elementary-xfce/apps/96/lightdm-gtk-greeter-settings.svg
- elementary-xfce/apps/96/lightdm-settings.svg
- elementary-xfce/apps/96/mugshot.svg
- elementary-xfce/status/16/avatar-default.svg
This adds a new lightdm icon and symlinks mugshot
to the avatar-default icon (both seen in Settings Manager).
Using the avatar icon should add some continuity
between login, profile, user-related actions.
It's uses the same icon that is used in the Whisker Menu, and
the login screen and mugshot placeholder before setting a user image.
> Add lightdm settings, mugshot icons

- elementary-xfce/actions/16/window-close.svg
Trying to ditch the monochrome close icon and make it more visible in light and dark themes.
Let me know what you think about the shape/design and color. If the red is too loud or anything else. And also if I should do the other sizes in the same style.
> Make window-close visible in dark and light themes

- elementary-xfce-darkest/actions
- elementary-xfce-darkest/index.theme
This variant used elementary-xfce as a fallback and
symlinked the faux symbolic toolbar icons from xfce-darker.
It now falls back entirely to elementary-xfce and
its description is changed to indicate this.
> Deprecate elementary-xfce-darkest

- elementary-xfce/actions/24/media-playback-pause-symbolic.svg
- elementary-xfce/actions/24/media-playback-start-symbolic-rtl.svg
- elementary-xfce/actions/24/media-playback-start-symbolic.svg
- elementary-xfce/actions/24/media-playback-stop-symbolic.svg
- elementary-xfce/actions/24/media-record-symbolic.svg
- elementary-xfce/actions/24/media-seek-backward-symbolic-rtl.svg
- elementary-xfce/actions/24/media-seek-backward-symbolic.svg
- elementary-xfce/actions/24/media-seek-forward-symbolic-rtl.svg
- elementary-xfce/actions/24/media-seek-forward-symbolic.svg
- elementary-xfce/actions/24/media-skip-backward-symbolic-rtl.svg
- elementary-xfce/actions/24/media-skip-backward-symbolic.svg
- elementary-xfce/actions/24/media-skip-forward-symbolic-rtl.svg
- elementary-xfce/actions/24/media-skip-forward-symbolic.svg
- elementary-xfce/actions/symbolic/media-skip-backward-symbolic.svg
- elementary-xfce/status/24/media-playlist-repeat-symbolic.svg
- elementary-xfce/status/24/media-playlist-shuffle-symbolic.svg
Adds symbolic media icons at 24px.
Adjust spacing for some symbolic media icons at 16px.
Fixes spacing and blurry-icon issues with
Rhythmbox (without alternative toolbar) and
Pulse Audio panel plugin for Xfce Panel.
> Symbolic media icons: Add at 24px, adjust at 16px

- elementary-xfce/categories/16/gtk-preferences.svg
- elementary-xfce/categories/24/gtk-preferences.svg
These were both pointing to the 32px icon.
Fixes #319
> Fix gtk-preferences symlinks at 16px and 24px

- elementary-xfce/apps/128/ubiquity.svg
- elementary-xfce/apps/16/ubiquity.svg
- elementary-xfce/apps/22/ubiquity.svg
- elementary-xfce/apps/24/ubiquity.svg
- elementary-xfce/apps/32/ubiquity.svg
- elementary-xfce/apps/48/ubiquity.svg
- elementary-xfce/apps/64/ubiquity.svg
- elementary-xfce/apps/96/ubiquity.svg
- elementary-xfce/apps/96/usb-creator-gtk.svg
- elementary-xfce/apps/96/usb-creator-kde.svg
Use the USB removable media icon instead of the CD icon for the Ubiquity and USB Creator icons.
For USB Creator, the icon now matches the application name.
For Ubiquity, when trying Xubuntu Live this icon will be seen as the "Install Xubuntu" icon on the desktop. USB media is likely what most people use now as disc drives have become more rare (and the live image size is greater than that of a CD now).
I know (as mentioned in #341) that this type of icon can become antiquated, so if there is a better solution (or if the CD still works just fine) let me know.
Thanks.
> Update Ubiquity and USB Creator icon

- elementary-xfce/categories/128/applications-multimedia.svg
- elementary-xfce/categories/16/applications-multimedia.svg
- elementary-xfce/categories/24/applications-multimedia.svg
- elementary-xfce/categories/32/applications-multimedia.svg
- elementary-xfce/categories/48/applications-multimedia.svg
- elementary-xfce/categories/64/applications-multimedia.svg
- elementary-xfce/categories/96/applications-multimedia.svg
- elementary-xfce/categories/symbolic/applications-multimedia-symbolic.svg
Proposal for a new multimedia category icon. This is more legible at small sizes, less busy, and easier to see in dark themes. The music note matches the audio mime icon in style and color.
> New multimedia category icon

- elementary-xfce/mimes/128/audio-flac.svg
- elementary-xfce/mimes/128/audio-x-wav.svg
- elementary-xfce/mimes/16/audio-flac.svg
- elementary-xfce/mimes/16/audio-x-wav.svg
- elementary-xfce/mimes/24/audio-flac.svg
- elementary-xfce/mimes/24/audio-x-wav.svg
- elementary-xfce/mimes/32/audio-flac.svg
- elementary-xfce/mimes/32/audio-x-wav.svg
- elementary-xfce/mimes/48/audio-flac.svg
- elementary-xfce/mimes/48/audio-x-wav.svg
- elementary-xfce/mimes/64/audio-flac.svg
- elementary-xfce/mimes/64/audio-x-wav.svg
- elementary-xfce/mimes/96/audio-flac.svg
- elementary-xfce/mimes/96/audio-x-wav.svg
Makes FLAC and WAV icons use a blue music symbol
to differentiate it from the orange music symbol.
The blue should now represent lossless audio, while the orange should now represent lossy audio.
> Mimes: Use different color for lossless audio icons

- elementary-xfce/actions/16/document-print.svg
- elementary-xfce/actions/24/document-print-preview.svg
- elementary-xfce/actions/24/document-print.svg
- elementary-xfce/actions/48/document-print-preview.svg
- elementary-xfce/actions/48/document-print.svg
- elementary-xfce/apps/16/system-config-printer.svg
- elementary-xfce/apps/24/system-config-printer.svg
- elementary-xfce/apps/32/system-config-printer.svg
- elementary-xfce/apps/48/system-config-printer.svg
- elementary-xfce/apps/64/system-config-printer.svg
- elementary-xfce/devices/16/gnome-dev-printer-new.svg
- elementary-xfce/devices/16/printer.svg
- elementary-xfce/devices/16/system-config-printer.svg
- elementary-xfce/devices/24/printer.svg
- elementary-xfce/devices/24/system-config-printer.svg
- elementary-xfce/devices/32/printer.svg
- elementary-xfce/devices/48/gnome-dev-printer-new.svg
- elementary-xfce/devices/48/printer-network.svg
- elementary-xfce/devices/48/printer.svg
- elementary-xfce/devices/48/system-config-printer.svg
- elementary-xfce/devices/64/gnome-dev-printer-new.svg
- elementary-xfce/devices/64/printer-network.svg
- elementary-xfce/devices/64/system-config-printer.svg
- elementary-xfce/status/16/printer-error.svg
- elementary-xfce/status/48/printer-error.svg
Updated
- Use semi-transparent borders on all printer icons for a sharper look (especially in dark themes)
- Replaced printer error `-` emblem with newer `!` symbol
- Move `system-config-printer` symlinks to `apps` directory
Added
- `printer` 32px
- `printer-error` 16px
> Devices: Sharpen printer icons, add sizes

- elementary-xfce/apps/128/org.gnome.Software.svg
- elementary-xfce/apps/128/system-software-installer.svg
- elementary-xfce/apps/16/org.gnome.Software.svg
- elementary-xfce/apps/16/system-software-installer.svg
- elementary-xfce/apps/24/org.gnome.Software.svg
- elementary-xfce/apps/24/system-software-installer.svg
- elementary-xfce/apps/32/org.gnome.Software.svg
- elementary-xfce/apps/32/system-software-installer.svg
- elementary-xfce/apps/48/org.gnome.Software.svg
- elementary-xfce/apps/48/system-software-installer.svg
- elementary-xfce/apps/64/org.gnome.Software.svg
- elementary-xfce/apps/64/system-software-installer.svg
- elementary-xfce/apps/96/org.gnome.Software.svg
- elementary-xfce/apps/96/system-software-installer.svg
User newer elementary gradients, borders, and arrow styles for `org.gnome.Software` and `system-software-installer`.
Split this one off from #344 as I think these are pretty uncontroversial. (any input on the discussion in #344 would be appreciated!)
Current (screenshots taken before softwarecenter changed to org.gnome.Software):
Proposed:
Oh, also, many app icons are symlinked to `system-software-installer`, which means they all use the same icon. Is this okay?
> Apps: Refresh software center icons

- elementary-xfce/actions/16/zoom-fit-best.svg
- elementary-xfce/actions/16/zoom-in.svg
- elementary-xfce/actions/16/zoom-original.svg
- elementary-xfce/actions/16/zoom-out.svg
- elementary-xfce/actions/24/zoom-fit-best.svg
- elementary-xfce/actions/24/zoom-in.svg
- elementary-xfce/actions/24/zoom-original.svg
- elementary-xfce/actions/24/zoom-out.svg
- elementary-xfce/actions/32/zoom-fit-best.svg
- elementary-xfce/actions/32/zoom-in.svg
- elementary-xfce/actions/32/zoom-original.svg
- elementary-xfce/actions/32/zoom-out.svg
- elementary-xfce/actions/48/zoom-fit-best.svg
- elementary-xfce/actions/48/zoom-in.svg
- elementary-xfce/actions/48/zoom-original.svg
- elementary-xfce/actions/48/zoom-out.svg
Adjust icon gradients and borders at 16px.
Fill symbols with lighter color to improve contrast at all sizes.
Should make the zoom icons more legible and uniform at all sizes, and 16px borders should look better in dark themes.
---
It's kind of subtle, but looks a lot better in use I think.
Current (left), Proposed (right):
Menus:
Toolbar:
> Actions: Make zoom icons uniform, add contrast

- svgtopng/pngtheme.sh
While updating the FreeBSD port I got failures due to cp failing to find some files, referenced by symlinks:
```
install -d /wrkdirs/usr/ports/x11-themes/xfce-icons-elementary/work/stage/usr/local/share/icons
cp -rf build/elementary-xfce /wrkdirs/usr/ports/x11-themes/xfce-icons-elementary/work/stage/usr/local/share/icons
cp: build/elementary-xfce/actions/24/go-previous-symbolic-rtl.png: No such file or directory
cp: build/elementary-xfce/actions/24/media-skip-forward-symbolic-rtl.png: No such file or directory
cp: build/elementary-xfce/actions/24/media-skip-backward-symbolic-rtl.png: No such file or directory
cp: build/elementary-xfce/actions/24/go-next-symbolic-rtl.png: No such file or directory
cp: build/elementary-xfce/actions/24/media-seek-forward-symbolic-rtl.png: No such file or …
```
> Do not convert 'symbolic-rtl' versions.

- elementary-xfce/status/symbolic/audio-volume-high-symbolic.svg
- elementary-xfce/status/symbolic/audio-volume-low-symbolic.svg
- elementary-xfce/status/symbolic/audio-volume-medium-symbolic.svg
- elementary-xfce/status/symbolic/audio-volume-muted-blocking-symbolic.svg
- elementary-xfce/status/symbolic/audio-volume-muted-symbolic.svg
- elementary-xfce/status/symbolic/audio-volume-overamplified-symbolic.svg
New symbolic audio icons to make size of status / systray icons more consistent.
Also uses the new strikethrough style for muted and blocking.
Addresses part of #152
Current:
Proposed:
---
This PR uses this style for `audio-volume-muted-symbolic` and `audio-volume-muted-blocking-symbolic`:
Here is an alternative, more like what upstream uses. When you go from audo low to mute, the icon "jumps" more (the speaker icon goes from left to center) and to me is a little less legible (the strikethrough sort of blocks what is behind it). But, it is cleaner looking:
Up to you on what looks better, I don't have a strong feeling either way. Here are the SVGs if you want to try them in-use.
> Status: Make symbolic audio icons bigger

- elementary-xfce/actions/16/system-lock-screen.svg
- elementary-xfce/actions/16/system-log-out.svg
- elementary-xfce/actions/16/system-reboot.svg
- elementary-xfce/actions/16/system-shutdown.svg
- elementary-xfce/actions/16/system-suspend-hibernate.svg
- elementary-xfce/actions/16/system-suspend.svg
- elementary-xfce/actions/16/system-switch-user.svg
- elementary-xfce/actions/24/system-lock-screen.svg
- elementary-xfce/actions/24/system-log-out.svg
- elementary-xfce/actions/24/system-reboot.svg
- elementary-xfce/actions/24/system-shutdown.svg
- elementary-xfce/actions/24/system-suspend-hibernate.svg
- elementary-xfce/actions/24/system-suspend.svg
- elementary-xfce/actions/24/system-switch-user.svg
- elementary-xfce/actions/32/system-lock-screen.svg
- elementary-xfce/actions/32/system-log-out.svg
- elementary-xfce/actions/32/system-reboot.svg
- elementary-xfce/actions/32/system-shutdown.svg
- elementary-xfce/actions/32/system-suspend-hibernate.svg
- elementary-xfce/actions/32/system-suspend.svg
- elementary-xfce/actions/32/system-switch-user.svg
- elementary-xfce/actions/48/system-lock-screen.svg
- elementary-xfce/actions/48/system-log-out.svg
- elementary-xfce/actions/48/system-reboot.svg
- elementary-xfce/actions/48/system-shutdown.svg
- elementary-xfce/actions/48/system-suspend-hibernate.svg
- elementary-xfce/actions/48/system-suspend.svg
- elementary-xfce/actions/48/system-switch-user.svg
~Changes colors of Session icons based on the safety level of their action.~
Update arrow style, borders, gradients, and shadows to better match elementary style. Hopefully they're a little cleaner and clearer. Also some sizes were missing so they were added.
Current:
Proposed:
---
Updates arrow style, borders, gradients, and shadows to better match elementary style. Should also make icons a little clearer and sharp looking.
Use green color for "safe" actions (Lock Screen and Switch User).
This should make them easier to see and look less like disabled icons (previously they were a greyish color).
Closes #351
> Actions: Update session icons

- elementary-xfce/status/128/un-reboot.svg
- elementary-xfce/status/16/software-update-available.svg
- elementary-xfce/status/16/software-update-urgent.svg
- elementary-xfce/status/16/un-reboot.svg
- elementary-xfce/status/22/software-update-available.svg
- elementary-xfce/status/22/software-update-urgent.svg
- elementary-xfce/status/22/un-reboot.svg
- elementary-xfce/status/24/un-reboot.svg
- elementary-xfce/status/32/un-reboot.svg
- elementary-xfce/status/48/un-reboot.svg
- elementary-xfce/status/64/un-reboot.svg
Add icon for update-notifier status notifier and dialog. A symlink to `software-update-available` it should now match the update available notification of Package Update Indicator.
Make 16px icons a little bigger to match other panel notification sizes. (some of the border spills out but still looks better than before when in use)
Fix issue where 22px update "available" and "urgent" icons didn't match other sizes.
> Status: Add update-notifier icon

- elementary-xfce/mimes/128/application-x-executable.svg
- elementary-xfce/mimes/16/application-x-executable.svg
- elementary-xfce/mimes/24/application-x-executable.svg
- elementary-xfce/mimes/32/application-x-executable.svg
- elementary-xfce/mimes/48/application-x-executable.svg
- elementary-xfce/mimes/64/application-x-executable.svg
- elementary-xfce/mimes/96/application-x-executable.svg
Symlink the Mime icon `application-x-executable` to the Category icon `applications-other`. It uses the same design as what is used currently but has better contrast, looks better on dark themes, and is used more widely in the theme to represent applications.
This will change the icon used for executable and binary mimes, as well as some executable-related actions like "Create Launcher..." on Xfdesktop right click.
---
The `applications-other` icon is used for:
- "All Applications" in Whisker Menu
- "Launcher" Xfce panel plugin
- "Applications" when right clicking on Xfdesktop
The white-square-with-gear is also used for .desktop files on Xfdesktop and thunar, and also more closely matches the icon used for other executable mimes like Appimage, Debs, RPMs, etc.
> Mimes: Use 'applications-other' for executables

- elementary-xfce/apps/128/stock_xfburn.svg
- elementary-xfce/apps/16/stock_xfburn.svg
- elementary-xfce/apps/22/stock_xfburn.svg
- elementary-xfce/apps/24/stock_xfburn.svg
- elementary-xfce/apps/32/stock_xfburn.svg
- elementary-xfce/apps/48/stock_xfburn.svg
- elementary-xfce/apps/64/stock_xfburn.svg
- elementary-xfce/apps/96/stock_xfburn.svg
Uses `animations/48/brasero-disc-60` animation step as base, updated with newer borders and palette.
Fixes #207
--- 
Wasn't sure if using an animation as an app icon was a great choice, I tried this one and Disc + Fire (from the Firewall icon), and I liked this one better.
> Apps: New Xfburn icon

- elementary-xfce/apps/128/preferences-desktop.svg
- elementary-xfce/apps/16/preferences-desktop.svg
- elementary-xfce/apps/24/preferences-desktop.svg
- elementary-xfce/apps/32/preferences-desktop.svg
- elementary-xfce/apps/48/preferences-desktop.svg
- elementary-xfce/apps/64/preferences-desktop.svg
Use newer style from upstream for `preferences-system`. A more simplified version of the previous style, and maybe goes a little better with the new session icons and newer rounded-square app icons.
This one was [deleted from upstream](https://github.com/elementary/icons/commit/bc2afafaa0d4a3f05306440c4368944bcf3a9d92) a little bit back, but still fits this theme well I think.
Current:
Proposed:
> Apps: New Settings Manager icon

- elementary-xfce/places/16/folder-pictures.svg
- elementary-xfce/places/22/folder-pictures.svg
- elementary-xfce/places/24/folder-pictures.svg
Use same icon as upstream uses for `folder-pictures` at 16px-24px.
This changes the look in the Places sidebar and for the folder icon in the file manager at these small pixel sizes.
---
A few possible issues. This doesn't match the image mimetype like the current one does. It is the same icon that was use for the "Graphics" category so it might be good to come up with something different for that category in the future. Just wanted to bring those up in case anyone thought these might be reasons not to merge this.
> Places: Use coloful "pictures" folder icon

- Makefile.in
- elementary-xfce-darker/AUTHORS
- elementary-xfce-darker/CONTRIBUTORS
- elementary-xfce-darker/LICENSE
- elementary-xfce-darker/README.md
- elementary-xfce-darker/index.theme
- elementary-xfce-darkest/AUTHORS
- elementary-xfce-darkest/CONTRIBUTORS
- elementary-xfce-darkest/LICENSE
- elementary-xfce-darkest/README.md
- elementary-xfce-darkest/index.theme
These have been deprecated for a while. The folders only contain symlinks to the regular and -dark theme, no actual content.
I wanted to wait until after the Xubuntu 24.04 LTS release for this to avoid any possible issues when upgrading from the previous LTS release. Xubuntu 24.04 defaults to -dark now, so I think we've done all we can to reduce any disruptions.
> Remove -darker and -darkest themes

- elementary-xfce/actions/16/document-save-as.svg
- elementary-xfce/actions/16/document-save.svg
- elementary-xfce/actions/22/document-save-as.svg
- elementary-xfce/actions/22/document-save.svg
- elementary-xfce/actions/24/document-save-as.svg
- elementary-xfce/actions/24/document-save.svg
- elementary-xfce/actions/32/document-save-as.svg
- elementary-xfce/actions/32/document-save.svg
- elementary-xfce/actions/48/document-save-as.svg
- elementary-xfce/actions/48/document-save.svg
- elementary-xfce/actions/symbolic/document-save-as-symbolic.svg
- elementary-xfce/actions/symbolic/document-save-symbolic.svg
New `document-save` and `document-save-as` icons from upstream.
"Save" uses new rounded-square "document action" (similar to the new import/export)
"Save as" uses the arrow into folder
Closes #341
> Actions: New save and save-as icons from upstream

- elementary-xfce/apps/128/system-file-manager.svg
- elementary-xfce/apps/16/system-file-manager.svg
- elementary-xfce/apps/22/system-file-manager.svg
- elementary-xfce/apps/24/system-file-manager.svg
- elementary-xfce/apps/32/system-file-manager.svg
- elementary-xfce/apps/48/system-file-manager.svg
- elementary-xfce/apps/64/system-file-manager.svg
- elementary-xfce/apps/96/system-file-manager.svg
Upstream redesigned the File Manager icon a while back, it's very nice.
This is a slight modification, replacing upstream's magnifying glass emblem (which we use for Catfish and "find" functions) with the home emblem which we currently use for the default file manager.
> Apps: New File Manager icon using upstream design

- elementary-xfce/index.theme
The FreeDesktop.org Icon Theme Spec has been updated stating that inherited themes should be present on the system (considered dependencies).
The currently listed themes in elementary-xfce's `Inherits` line are either no longer developed and missing modern icons (gnome), or have reduced the scope of their theme to focus on their OS (Adwaita, elementary).
elementary-xfce should currently be robust enough that it should already include the icons found in these themes. So it no longer seems very necessary to keep these, and removing them will prevent unnecessary themes from being forced as dependencies for users who may not want them.
Fixes #458
> Remove inherited themes from index.theme

- .github/workflows/pull-request.yml
Getting an error when doing PRs, worflow says it needs v4 actions: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Update github workflow artifact-action version

- elementary-xfce/emblems/16/emblem-readonly.svg
- elementary-xfce/emblems/16/emblem-unreadable.svg
- elementary-xfce/emblems/22/emblem-readonly.svg
- elementary-xfce/emblems/22/emblem-unreadable.svg
- elementary-xfce/emblems/24/emblem-readonly.svg
- elementary-xfce/emblems/24/emblem-unreadable.svg
- elementary-xfce/emblems/32/emblem-readonly.svg
- elementary-xfce/emblems/32/emblem-unreadable.svg
- elementary-xfce/emblems/48/emblem-readonly.svg
- elementary-xfce/emblems/48/emblem-unreadable.svg
Debian was marking these as CC-BY-SA-2.0. I believe they were originally Gnome icons which were relicensed from CC-BY-SA-2.0 to GPL-2-or-later but I'm not totally sure. So best to replace them as newly made GPL3 icons.
This combines the color of the error emblem with the metaphor of the existing read/write restricted emblems.
They may be a little loud. Going to go ahead and replace them just to be sure of licensing stuff, but if there are any complaints as to the colors we can change that later.
> Emblems: Update read/write restricted emblems

- .github/workflows/pull-request.yml
- .github/workflows/symlinks-check.yml
There seems to be some issue with the png to svg
conversion in the github actions workflow when
using `ubuntu-latest` (which is currently Ubuntu 24.04).
This is resolved by using `ubuntu-22.04`.
Not sure why this happens, I've tested on Ubuntu 24.04
on my machine (and VM) and do not get the build errors.
This fix feels like a band-aid but it works for now.
> Fix workflow not building icon theme correctly

- elementary-xfce/apps/128/accessories-screenshot-tool.svg
- elementary-xfce/apps/16/accessories-screenshot-tool.svg
- elementary-xfce/apps/22/accessories-screenshot-tool.svg
- elementary-xfce/apps/24/accessories-screenshot-tool.svg
- elementary-xfce/apps/32/accessories-screenshot-tool.svg
- elementary-xfce/apps/48/accessories-screenshot-tool.svg
- elementary-xfce/apps/64/accessories-screenshot-tool.svg
- elementary-xfce/apps/96/accessories-screenshot-tool.svg
While we have an Xfce-specific screenshot app icon, the FreeDesktop.Org named `accessories-screenshot-tool` app icon was missing. This adds the icon pulled from upstream and created missing sizes.
> Apps: Add screenshot tool from upstream

- elementary-xfce/apps/128/htop.svg
- elementary-xfce/apps/16/htop.svg
- elementary-xfce/apps/22/htop.svg
- elementary-xfce/apps/32/htop.svg
- elementary-xfce/apps/48/htop.svg
- elementary-xfce/apps/64/htop.svg
- elementary-xfce/apps/96/htop.svg
Replace htop symlink, which pointed to task manager, with unique htop icon closer to its original design using the terminal icon as the base.
There is some variance in look between sizes. Some of it is a bit unavoidable trying to keep it all grid-aligned. But I wasn't sure if going for the more obvious "H" was better (like in 96, 128px) or a little closer to the original logo (like the 32px one). Any input would be appreciated!
> Apps: Add htop icon

- elementary-xfce/mimetypes/128/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/128/application-x-msdownload.svg
- elementary-xfce/mimetypes/16/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/16/application-x-msdownload.svg
- elementary-xfce/mimetypes/24/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/24/application-x-msdownload.svg
- elementary-xfce/mimetypes/32/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/32/application-x-msdownload.svg
- elementary-xfce/mimetypes/48/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/48/application-x-msdownload.svg
- elementary-xfce/mimetypes/64/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/64/application-x-msdownload.svg
- elementary-xfce/mimetypes/96/application-vnd.microsoft.portable-executable.svg
- elementary-xfce/mimetypes/96/application-x-msdownload.svg
Updates the `exe` icon to look more rounded like other executables. Colors depart from upstream slightly as the darker upstream color with darker emblem is somewhat difficult to see. This one uses a stronger contrast between the two.
Add a `portable-executable` symlink as some `exe` files were not using the correct icon. Now all files with the `exe` extension will get the same icon.
This has the unfortunate side effect that `dll` files will also use this icon, but that's an issue with the FreeDesktop.org shared-mime-info database. Until they're given unique entries in the database (if possible), they'll have to share an icon.
> MimeTypes: Refresh exe icon, add missing symlink

- elementary-xfce/mimetypes/32/application-gzip.svg
- elementary-xfce/mimetypes/32/application-java-archive.svg
- elementary-xfce/mimetypes/32/application-vnd.ms-cab-compressed.svg
- elementary-xfce/mimetypes/32/application-vnd.rar.svg
- elementary-xfce/mimetypes/32/application-x-7z-compressed.svg
- elementary-xfce/mimetypes/32/application-x-ace.svg
- elementary-xfce/mimetypes/32/application-x-archive.svg
- elementary-xfce/mimetypes/32/application-x-arj.svg
- elementary-xfce/mimetypes/32/application-x-bzip2-compressed-tar.svg
- elementary-xfce/mimetypes/32/application-x-bzip2.svg
- elementary-xfce/mimetypes/32/application-x-compressed-tar.svg
- elementary-xfce/mimetypes/32/application-x-cpio.svg
- elementary-xfce/mimetypes/32/application-x-lha.svg
- elementary-xfce/mimetypes/32/application-x-lhz.svg
- elementary-xfce/mimetypes/32/application-x-lzma-compressed-tar.svg
- elementary-xfce/mimetypes/32/application-x-lzma.svg
- elementary-xfce/mimetypes/32/application-x-lzop.svg
- elementary-xfce/mimetypes/32/application-x-pak.svg
- elementary-xfce/mimetypes/32/application-x-par2.svg
- elementary-xfce/mimetypes/32/application-x-shar.svg
- elementary-xfce/mimetypes/32/application-x-stuffit.svg
- elementary-xfce/mimetypes/32/application-x-tar.svg
- elementary-xfce/mimetypes/32/application-x-xz-compressed-tar.svg
- elementary-xfce/mimetypes/32/application-x-xz.svg
- elementary-xfce/mimetypes/32/application-x-zoo.svg
- elementary-xfce/mimetypes/32/application-zip.svg
Tries to use the text from the 48px icons untouched. Proportionally the text is larger compared to the icon, but keeping the 48px text size makes it more legible.
A few had to be made a bit smaller to fit, some shortened (tar.xyz shortened to t.xyz for example).
Any input would be appreciated!
--
#523 should be merged before this one so that the `application-x-archive` icon doesn't only exist at 32px.
> MimeTypes: Add text to 32px archive icons

- elementary-xfce/index-hidpi.theme
FreeDesktop.org Icon Theme spec was updated stating that inherited themes should be present on the system if the icon theme is to be installed (inhereted themes considered dependencies).
This just follows the change to the main theme made previously.
See #461
> Index: Remove inherited themes from HiDPI
